services:
  transcendence:
    build: .
    restart: unless-stopped
    env_file: .env.prod
    environment:
      DATABASE_URL: file:/data/database.db
    volumes:
      - ./data/:/data

  caddy:
    depends_on:
      - transcendence
    image: caddy:2.11.3-alpine
    restart: unless-stopped
    ports:
      - 4443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certs:/etc/caddy/certs:ro
