services:
  transcendence:
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file: .env.prod
    environment:
      DATABASE_URL: file:/data/database.db
      AVATAR_DIR: /data/avatar
    volumes:
      - ./data/:/data
