packages:
  - 'docusaurus'
blockExoticSubdeps: false
allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
engineStrict: true
publicHoistPattern:
  - '@colyseus/*'
patchedDependencies:
  '@colyseus/tools@0.17.19': patches/@colyseus__tools@0.17.19.patch
